export const userConstants = {
    REGISTER_REQUEST: 'REGISTER_REQUEST',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOG_OUT: 'USERS_LOGOUT',

    GET_USER: 'GET_USER',
}